# Generated by Django 5.0.2 on 2024-02-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_task_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
